#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 28 16:02:11 2018

@author: sanjotraibagkar
"""

import talib
import nsepy
from nsepy import get_history
from datetime import date
import pandas as pd
from matplotlib import pyplot as plt 
import numpy as np


nifty = get_history(symbol="NIFTY", 
                    start=date(2015,1,1), 
                    end=date(2018,4,27),
					index=True)

upper_band, _, lower_band = talib.BBANDS(  
    nifty.Close.values,  
    nbdevup = 2, nbdevdn = 2,  
    matype = 0)  

nifty["upperband"] = upper_band
nifty["lowerband"] = lower_band

print(nifty.head())





plt.figure(1,figsize=(10,9))
plt.subplot(211)
plt.title("BB")
plt.plot(nifty.Close, label= 'Nifty')
plt.plot(nifty.Close.rolling(200).mean(),label ="MA")
plt.plot(nifty.upperband,label ="upper")
plt.plot(nifty.lowerband,label ="lowerband")
#plt.plot(lower_band,label ="lower")
plt.legend(['MA', 'MA_mean'])
plt.show()